### ISSUE TITLE
[Windows] Runs out of memory at 1012,5 MB

### ISSUE THREAD

**Issue by MrDobilina** [Luzifer/ed-fast-travel#7]
Using windows 10 latest update, I run the exe that you have linked here and it pops up says it is loading the database and then instantly closes without allowing me to do anything at all. No gui, no command line.

Also I can't figure out how the web based version is meant to work.

**Comment by Luzifer** [comment]
Please try this:
- Press <kbd>Win</kbd>+<kbd>R</kbd>
- Enter `cmd` and press <kbd>enter</kbd>
- Pull the `.exe` from your Explorer into the terminal window (it should put its path into the commandline)
- Press <kbd>enter</kbd> in the terminal window

If this outputs an error please copy it here for me to debug the issue further.

**Comment by MrDobilina** [comment]
The amd64 ran fine the non 64 had an error:

511758/3297541 [====================>--------------------------------------------------------------------------------------------------------------------] 15.52% 2sruntime: out of memory : cannot allocate 786432-byte block (1061683200 in use)
fatal error: out of memory

16gb ram here so shouldn't have an issue

**Comment by Luzifer** [comment]
Hmm which version are you using?

`ed-fast-travel.exe --version`

Your pasted message states it uses ~1 GB of memory and has only loaded 15% of the database… That definitely looks strange as it should not use that much of memory. I've seen peaks of roughly 1.5GB memory usage while testing…

**Comment by Luzifer** [comment]
> The amd64 ran fine the non 64 had an error

Didn't see that comment… In that case the 32bit version seems to have issues allocating more than 1G memory.
