### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by tonkepen100** [Luzifer/ed-fast-travel#9]
Hello, if you wish, I will translate it into Spanish.

Admin@piro.biz or TS3 = ts.piro.biz

Thanks

**Comment by Luzifer** [comment]
Thank you very much for your offer. Looks like I forgot to reply to this 😞 …

To translate to spanish you'd take the [en-US.all.yaml](https://github.com/Luzifer/ed-fast-travel/blob/master/i18n/en-US.all.yaml) file and replace the `translation` strings with their respective Spanish version.

There is only one template in the translations (`{{.WebRouteStopMin | printf "%.0f"}}`) which will result in a number (by default 500) - you can just copy that to your translation.
